2025-03-05 20:10:10,719 - connexion.middleware.main - WARNING - `ConnexionMiddleware.run` is optimized for development. For production, run using a dedicated ASGI server.
2025-03-05 20:10:10,723 - asyncio - DEBUG - Using proactor: IocpProactor
2025-03-05 20:10:10,772 - connexion.middleware.abstract - DEBUG - Adding /my-first-event...
2025-03-05 20:10:10,795 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:10:10,795 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:10:10,795 - connexion.middleware.abstract - DEBUG - Adding /other-event...
2025-03-05 20:10:10,796 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:10:10,796 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:10:10,805 - connexion.middleware.abstract - DEBUG - Adding /stats...
2025-03-05 20:10:10,806 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:10:10,806 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:10:10,808 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:10:10,808 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:10:10,808 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:10:10,808 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:10:10,809 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:10:10,809 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:10:10,809 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:10:10,809 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:10:10,810 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:10:10,810 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:10:10,810 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:10:10,810 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:10:10,810 - connexion.middleware.validation - DEBUG - Strict Request Validation: True
2025-03-05 20:10:10,811 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:10:10,811 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:10:10,811 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:10:10,811 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:10:10,811 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:10:10,812 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:10:10,812 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:10:10,812 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:10:10,812 - connexion.middleware.security - DEBUG - ... Security: None
2025-03-05 20:10:10,813 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:10:10,813 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:10:10,813 - connexion.middleware.security - DEBUG - ... Security: None
2025-03-05 20:10:10,813 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:10:10,814 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:10:10,814 - connexion.middleware.security - DEBUG - ... Security: None
2025-03-05 20:10:10,814 - connexion.middleware.abstract - DEBUG - Adding /my-first-event...
2025-03-05 20:10:10,814 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:10:10,815 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:10:10,815 - connexion.middleware.abstract - DEBUG - Adding /other-event...
2025-03-05 20:10:10,815 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:10:10,815 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:10:10,816 - connexion.middleware.abstract - DEBUG - Adding /stats...
2025-03-05 20:10:10,816 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:10:10,816 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:10:10,816 - connexion.middleware.swagger_ui - INFO - Adding spec json: /openapi.json
2025-03-05 20:10:10,817 - connexion.middleware.swagger_ui - DEBUG - Adding spec yaml: //openapi.yaml
2025-03-05 20:10:10,818 - connexion.middleware.swagger_ui - DEBUG - Adding swagger-ui: /ui/
2025-03-05 20:10:19,797 - connexion.validators.parameter - DEBUG - /my-first-event validating parameters...
2025-03-05 20:10:19,799 - connexion.decorators.parameter - DEBUG - Query Parameter 'index' (sanitized: 'index') in function arguments
2025-03-05 20:10:19,800 - connexion.decorators.parameter - DEBUG - index is a {'name': 'index', 'in': 'query', 'required': True, 'description': 'The index of the player-performance event in the Kafka queue.', 'schema': {'type': 'integer', 'example': 0}}
2025-03-05 20:10:19,802 - pykafka.cluster - INFO - Broker version is too old to use automatic API version discovery. Falling back to hardcoded versions list.
2025-03-05 20:10:19,805 - pykafka.cluster - DEBUG - Updating cluster, attempt 1/3
2025-03-05 20:10:19,805 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:10:19,814 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:10:19,827 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:10:19,829 - pykafka.cluster - INFO - Discovered 1 brokers
2025-03-05 20:10:19,829 - pykafka.cluster - DEBUG - Discovered broker id 1001: b'localhost':9092
2025-03-05 20:10:19,830 - pykafka.connection - DEBUG - Connecting to b'localhost':9092
2025-03-05 20:10:19,831 - pykafka.connection - DEBUG - Successfully connected to b'localhost':9092
2025-03-05 20:10:19,832 - pykafka.cluster - INFO - Discovered 1 topics
2025-03-05 20:10:19,832 - pykafka.cluster - DEBUG - Discovered topic 'b'events''
2025-03-05 20:10:19,833 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:10:19,835 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:10:19,844 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:10:19,844 - pykafka.topic - INFO - Adding 1 partitions
2025-03-05 20:10:19,845 - pykafka.topic - DEBUG - Adding partition b'events'/0
2025-03-05 20:10:19,845 - pykafka.simpleconsumer - INFO - Resetting offsets for 1 partitions
2025-03-05 20:10:19,849 - pykafka.simpleconsumer - INFO - Flushed queue for partition 0
2025-03-05 20:10:19,850 - pykafka.simpleconsumer - INFO - Starting 1 fetcher threads
2025-03-05 20:10:20,842 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:10:20,858 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:10:20,858 - basicLogger - INFO - Found 0 player-performance events in Kafka
2025-03-05 20:10:20,863 - connexion.validators.parameter - DEBUG - /my-first-event validating parameters...
2025-03-05 20:10:20,864 - connexion.decorators.parameter - DEBUG - Query Parameter 'index' (sanitized: 'index') in function arguments
2025-03-05 20:10:20,864 - connexion.decorators.parameter - DEBUG - index is a {'name': 'index', 'in': 'query', 'required': True, 'description': 'The index of the player-performance event in the Kafka queue.', 'schema': {'type': 'integer', 'example': 0}}
2025-03-05 20:10:20,864 - pykafka.cluster - INFO - Broker version is too old to use automatic API version discovery. Falling back to hardcoded versions list.
2025-03-05 20:10:20,865 - pykafka.cluster - DEBUG - Updating cluster, attempt 1/3
2025-03-05 20:10:20,865 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:10:20,866 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:10:20,867 - pykafka.simpleconsumer - DEBUG - Finalising <pykafka.simpleconsumer.SimpleConsumer at 0x22aabbcdb10 (consumer_group=None)>
2025-03-05 20:10:20,869 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:10:20,869 - pykafka.simpleconsumer - DEBUG - Attempt to cleanup consumer failed
2025-03-05 20:10:20,869 - pykafka.simpleconsumer - ERROR - weakly-referenced object no longer exists
Traceback (most recent call last):
  File "C:\Users\ghier\AppData\Local\Programs\Python\Python311\Lib\site-packages\pykafka\simpleconsumer.py", line 449, in fetcher
    self.cleanup()
    ^^^^^^^^^^^^
ReferenceError: weakly-referenced object no longer exists
2025-03-05 20:10:20,871 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:10:20,871 - pykafka.simpleconsumer - DEBUG - Fetcher thread exiting
2025-03-05 20:10:20,872 - pykafka.cluster - INFO - Discovered 1 brokers
2025-03-05 20:10:20,872 - pykafka.cluster - DEBUG - Discovered broker id 1001: b'localhost':9092
2025-03-05 20:10:20,872 - pykafka.connection - DEBUG - Connecting to b'localhost':9092
2025-03-05 20:10:20,874 - pykafka.connection - DEBUG - Successfully connected to b'localhost':9092
2025-03-05 20:10:20,874 - pykafka.cluster - INFO - Discovered 1 topics
2025-03-05 20:10:20,875 - pykafka.cluster - DEBUG - Discovered topic 'b'events''
2025-03-05 20:10:20,875 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:10:20,890 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:10:20,895 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:10:20,895 - pykafka.topic - INFO - Adding 1 partitions
2025-03-05 20:10:20,895 - pykafka.topic - DEBUG - Adding partition b'events'/0
2025-03-05 20:10:20,897 - pykafka.simpleconsumer - INFO - Resetting offsets for 1 partitions
2025-03-05 20:10:20,898 - pykafka.simpleconsumer - INFO - Flushed queue for partition 0
2025-03-05 20:10:20,899 - pykafka.simpleconsumer - INFO - Starting 1 fetcher threads
2025-03-05 20:10:21,881 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:10:21,881 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:10:21,897 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:10:21,913 - basicLogger - INFO - Found 0 player-performance events in Kafka
2025-03-05 20:10:21,914 - pykafka.simpleconsumer - DEBUG - Finalising <pykafka.simpleconsumer.SimpleConsumer at 0x22aabffa190 (consumer_group=None)>
2025-03-05 20:10:21,914 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:10:21,915 - pykafka.simpleconsumer - DEBUG - Attempt to cleanup consumer failed
2025-03-05 20:10:21,916 - pykafka.simpleconsumer - ERROR - weakly-referenced object no longer exists
Traceback (most recent call last):
  File "C:\Users\ghier\AppData\Local\Programs\Python\Python311\Lib\site-packages\pykafka\simpleconsumer.py", line 449, in fetcher
    self.cleanup()
    ^^^^^^^^^^^^
ReferenceError: weakly-referenced object no longer exists
2025-03-05 20:10:21,919 - pykafka.simpleconsumer - DEBUG - Fetcher thread exiting
2025-03-05 20:10:21,921 - connexion.validators.parameter - DEBUG - /other-event validating parameters...
2025-03-05 20:10:21,923 - connexion.decorators.parameter - DEBUG - Query Parameter 'index' (sanitized: 'index') in function arguments
2025-03-05 20:10:21,923 - connexion.decorators.parameter - DEBUG - index is a {'name': 'index', 'in': 'query', 'required': True, 'description': 'The index of the audience-interaction event in the Kafka queue.', 'schema': {'type': 'integer', 'example': 0}}
2025-03-05 20:10:21,924 - pykafka.cluster - INFO - Broker version is too old to use automatic API version discovery. Falling back to hardcoded versions list.
2025-03-05 20:10:21,924 - pykafka.cluster - DEBUG - Updating cluster, attempt 1/3
2025-03-05 20:10:21,925 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:10:21,926 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:10:21,930 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:10:21,932 - pykafka.cluster - INFO - Discovered 1 brokers
2025-03-05 20:10:21,933 - pykafka.cluster - DEBUG - Discovered broker id 1001: b'localhost':9092
2025-03-05 20:10:21,933 - pykafka.connection - DEBUG - Connecting to b'localhost':9092
2025-03-05 20:10:21,934 - pykafka.connection - DEBUG - Successfully connected to b'localhost':9092
2025-03-05 20:10:21,934 - pykafka.cluster - INFO - Discovered 1 topics
2025-03-05 20:10:21,935 - pykafka.cluster - DEBUG - Discovered topic 'b'events''
2025-03-05 20:10:21,935 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:10:21,959 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:10:21,962 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:10:21,962 - pykafka.topic - INFO - Adding 1 partitions
2025-03-05 20:10:21,962 - pykafka.topic - DEBUG - Adding partition b'events'/0
2025-03-05 20:10:21,963 - pykafka.simpleconsumer - INFO - Resetting offsets for 1 partitions
2025-03-05 20:10:21,965 - pykafka.simpleconsumer - INFO - Flushed queue for partition 0
2025-03-05 20:10:21,965 - pykafka.simpleconsumer - INFO - Starting 1 fetcher threads
2025-03-05 20:10:22,928 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:10:22,943 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:10:22,974 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:10:22,974 - basicLogger - INFO - Found 0 audience-interaction events in Kafka
2025-03-05 20:10:22,978 - connexion.validators.parameter - DEBUG - /other-event validating parameters...
2025-03-05 20:10:22,978 - pykafka.simpleconsumer - DEBUG - Finalising <pykafka.simpleconsumer.SimpleConsumer at 0x22aabba5b10 (consumer_group=None)>
2025-03-05 20:10:22,980 - connexion.decorators.parameter - DEBUG - Query Parameter 'index' (sanitized: 'index') in function arguments
2025-03-05 20:10:22,980 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:10:22,980 - connexion.decorators.parameter - DEBUG - index is a {'name': 'index', 'in': 'query', 'required': True, 'description': 'The index of the audience-interaction event in the Kafka queue.', 'schema': {'type': 'integer', 'example': 0}}
2025-03-05 20:10:22,980 - pykafka.simpleconsumer - DEBUG - Attempt to cleanup consumer failed
2025-03-05 20:10:22,980 - pykafka.cluster - INFO - Broker version is too old to use automatic API version discovery. Falling back to hardcoded versions list.
2025-03-05 20:10:22,980 - pykafka.simpleconsumer - ERROR - weakly-referenced object no longer exists
Traceback (most recent call last):
  File "C:\Users\ghier\AppData\Local\Programs\Python\Python311\Lib\site-packages\pykafka\simpleconsumer.py", line 449, in fetcher
    self.cleanup()
    ^^^^^^^^^^^^
ReferenceError: weakly-referenced object no longer exists
2025-03-05 20:10:22,980 - pykafka.cluster - DEBUG - Updating cluster, attempt 1/3
2025-03-05 20:10:22,982 - pykafka.simpleconsumer - DEBUG - Fetcher thread exiting
2025-03-05 20:10:22,982 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:10:22,983 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:10:22,988 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:10:22,988 - pykafka.cluster - INFO - Discovered 1 brokers
2025-03-05 20:10:22,988 - pykafka.cluster - DEBUG - Discovered broker id 1001: b'localhost':9092
2025-03-05 20:10:22,989 - pykafka.connection - DEBUG - Connecting to b'localhost':9092
2025-03-05 20:10:22,991 - pykafka.connection - DEBUG - Successfully connected to b'localhost':9092
2025-03-05 20:10:22,991 - pykafka.cluster - INFO - Discovered 1 topics
2025-03-05 20:10:22,992 - pykafka.cluster - DEBUG - Discovered topic 'b'events''
2025-03-05 20:10:22,992 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:10:22,994 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:10:22,998 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:10:22,998 - pykafka.topic - INFO - Adding 1 partitions
2025-03-05 20:10:22,998 - pykafka.topic - DEBUG - Adding partition b'events'/0
2025-03-05 20:10:22,998 - pykafka.simpleconsumer - INFO - Resetting offsets for 1 partitions
2025-03-05 20:10:23,001 - pykafka.simpleconsumer - INFO - Flushed queue for partition 0
2025-03-05 20:10:23,001 - pykafka.simpleconsumer - INFO - Starting 1 fetcher threads
2025-03-05 20:10:23,984 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:10:23,999 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:10:23,999 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:10:24,015 - basicLogger - INFO - Found 0 audience-interaction events in Kafka
2025-03-05 20:10:24,018 - connexion.validators.parameter - DEBUG - /stats validating parameters...
2025-03-05 20:10:24,019 - pykafka.cluster - INFO - Broker version is too old to use automatic API version discovery. Falling back to hardcoded versions list.
2025-03-05 20:10:24,020 - pykafka.cluster - DEBUG - Updating cluster, attempt 1/3
2025-03-05 20:10:24,020 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:10:24,021 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:10:24,023 - pykafka.simpleconsumer - DEBUG - Finalising <pykafka.simpleconsumer.SimpleConsumer at 0x22aabffb250 (consumer_group=None)>
2025-03-05 20:10:24,023 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:10:24,024 - pykafka.simpleconsumer - DEBUG - Attempt to cleanup consumer failed
2025-03-05 20:10:24,025 - pykafka.simpleconsumer - ERROR - weakly-referenced object no longer exists
Traceback (most recent call last):
  File "C:\Users\ghier\AppData\Local\Programs\Python\Python311\Lib\site-packages\pykafka\simpleconsumer.py", line 449, in fetcher
    self.cleanup()
    ^^^^^^^^^^^^
ReferenceError: weakly-referenced object no longer exists
2025-03-05 20:10:24,025 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:10:24,025 - pykafka.simpleconsumer - DEBUG - Fetcher thread exiting
2025-03-05 20:10:24,026 - pykafka.cluster - INFO - Discovered 1 brokers
2025-03-05 20:10:24,026 - pykafka.cluster - DEBUG - Discovered broker id 1001: b'localhost':9092
2025-03-05 20:10:24,026 - pykafka.connection - DEBUG - Connecting to b'localhost':9092
2025-03-05 20:10:24,028 - pykafka.connection - DEBUG - Successfully connected to b'localhost':9092
2025-03-05 20:10:24,029 - pykafka.cluster - INFO - Discovered 1 topics
2025-03-05 20:10:24,030 - pykafka.cluster - DEBUG - Discovered topic 'b'events''
2025-03-05 20:10:24,031 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:10:24,033 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:10:24,038 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:10:24,038 - pykafka.topic - INFO - Adding 1 partitions
2025-03-05 20:10:24,038 - pykafka.topic - DEBUG - Adding partition b'events'/0
2025-03-05 20:10:24,039 - pykafka.simpleconsumer - INFO - Resetting offsets for 1 partitions
2025-03-05 20:10:24,041 - pykafka.simpleconsumer - INFO - Flushed queue for partition 0
2025-03-05 20:10:24,041 - pykafka.simpleconsumer - INFO - Starting 1 fetcher threads
2025-03-05 20:10:25,027 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:10:25,027 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:10:25,043 - basicLogger - INFO - Event stats computed: {'num_player_performance': 0, 'num_audience_interaction': 0}
2025-03-05 20:10:25,043 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:10:25,062 - pykafka.simpleconsumer - DEBUG - Finalising <pykafka.simpleconsumer.SimpleConsumer at 0x22aab2c38d0 (consumer_group=None)>
2025-03-05 20:10:25,062 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:10:25,062 - pykafka.simpleconsumer - DEBUG - Attempt to cleanup consumer failed
2025-03-05 20:10:25,063 - pykafka.simpleconsumer - ERROR - weakly-referenced object no longer exists
Traceback (most recent call last):
  File "C:\Users\ghier\AppData\Local\Programs\Python\Python311\Lib\site-packages\pykafka\simpleconsumer.py", line 449, in fetcher
    self.cleanup()
    ^^^^^^^^^^^^
ReferenceError: weakly-referenced object no longer exists
2025-03-05 20:10:25,063 - pykafka.simpleconsumer - DEBUG - Fetcher thread exiting
2025-03-05 20:10:26,071 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:13:43,340 - connexion.middleware.main - WARNING - `ConnexionMiddleware.run` is optimized for development. For production, run using a dedicated ASGI server.
2025-03-05 20:13:43,345 - asyncio - DEBUG - Using proactor: IocpProactor
2025-03-05 20:13:43,424 - connexion.middleware.abstract - DEBUG - Adding /my-first-event...
2025-03-05 20:13:43,463 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:13:43,464 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:13:43,464 - connexion.middleware.abstract - DEBUG - Adding /other-event...
2025-03-05 20:13:43,464 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:13:43,465 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:13:43,466 - connexion.middleware.abstract - DEBUG - Adding /stats...
2025-03-05 20:13:43,466 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:13:43,466 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:13:43,468 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:13:43,469 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:13:43,470 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:13:43,470 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:13:43,472 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:13:43,473 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:13:43,473 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:13:43,474 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:13:43,475 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:13:43,476 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:13:43,476 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:13:43,477 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:13:43,477 - connexion.middleware.validation - DEBUG - Strict Request Validation: True
2025-03-05 20:13:43,478 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:13:43,479 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:13:43,479 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:13:43,480 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:13:43,481 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:13:43,482 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:13:43,484 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:13:43,485 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:13:43,487 - connexion.middleware.security - DEBUG - ... Security: None
2025-03-05 20:13:43,488 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:13:43,489 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:13:43,490 - connexion.middleware.security - DEBUG - ... Security: None
2025-03-05 20:13:43,490 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:13:43,491 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:13:43,491 - connexion.middleware.security - DEBUG - ... Security: None
2025-03-05 20:13:43,492 - connexion.middleware.abstract - DEBUG - Adding /my-first-event...
2025-03-05 20:13:43,494 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:13:43,496 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:13:43,499 - connexion.middleware.abstract - DEBUG - Adding /other-event...
2025-03-05 20:13:43,501 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:13:43,502 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:13:43,504 - connexion.middleware.abstract - DEBUG - Adding /stats...
2025-03-05 20:13:43,506 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:13:43,507 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:13:43,515 - connexion.middleware.swagger_ui - INFO - Adding spec json: /openapi.json
2025-03-05 20:13:43,517 - connexion.middleware.swagger_ui - DEBUG - Adding spec yaml: //openapi.yaml
2025-03-05 20:13:43,526 - connexion.middleware.swagger_ui - DEBUG - Adding swagger-ui: /ui/
2025-03-05 20:13:55,745 - connexion.validators.parameter - DEBUG - /my-first-event validating parameters...
2025-03-05 20:13:55,748 - connexion.decorators.parameter - DEBUG - Query Parameter 'index' (sanitized: 'index') in function arguments
2025-03-05 20:13:55,749 - connexion.decorators.parameter - DEBUG - index is a {'name': 'index', 'in': 'query', 'required': True, 'description': 'The index of the player-performance event in the Kafka queue.', 'schema': {'type': 'integer', 'example': 0}}
2025-03-05 20:13:55,749 - pykafka.cluster - INFO - Broker version is too old to use automatic API version discovery. Falling back to hardcoded versions list.
2025-03-05 20:13:55,749 - pykafka.cluster - DEBUG - Updating cluster, attempt 1/3
2025-03-05 20:13:55,750 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:13:55,770 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:13:55,775 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:13:55,775 - pykafka.cluster - INFO - Discovered 1 brokers
2025-03-05 20:13:55,776 - pykafka.cluster - DEBUG - Discovered broker id 1001: b'localhost':9092
2025-03-05 20:13:55,776 - pykafka.connection - DEBUG - Connecting to b'localhost':9092
2025-03-05 20:13:55,778 - pykafka.connection - DEBUG - Successfully connected to b'localhost':9092
2025-03-05 20:13:55,778 - pykafka.cluster - INFO - Discovered 1 topics
2025-03-05 20:13:55,778 - pykafka.cluster - DEBUG - Discovered topic 'b'events''
2025-03-05 20:13:55,779 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:13:55,801 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:13:55,804 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:13:55,805 - pykafka.topic - INFO - Adding 1 partitions
2025-03-05 20:13:55,805 - pykafka.topic - DEBUG - Adding partition b'events'/0
2025-03-05 20:13:55,806 - pykafka.simpleconsumer - INFO - Resetting offsets for 1 partitions
2025-03-05 20:13:55,809 - pykafka.simpleconsumer - INFO - Flushed queue for partition 0
2025-03-05 20:13:55,809 - pykafka.simpleconsumer - INFO - Starting 1 fetcher threads
2025-03-05 20:13:56,781 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:13:56,811 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:13:56,811 - basicLogger - INFO - Found 0 player-performance events in Kafka
2025-03-05 20:13:56,817 - connexion.validators.parameter - DEBUG - /my-first-event validating parameters...
2025-03-05 20:13:56,818 - connexion.decorators.parameter - DEBUG - Query Parameter 'index' (sanitized: 'index') in function arguments
2025-03-05 20:13:56,819 - connexion.decorators.parameter - DEBUG - index is a {'name': 'index', 'in': 'query', 'required': True, 'description': 'The index of the player-performance event in the Kafka queue.', 'schema': {'type': 'integer', 'example': 0}}
2025-03-05 20:13:56,819 - pykafka.cluster - INFO - Broker version is too old to use automatic API version discovery. Falling back to hardcoded versions list.
2025-03-05 20:13:56,819 - pykafka.cluster - DEBUG - Updating cluster, attempt 1/3
2025-03-05 20:13:56,820 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:13:56,834 - pykafka.simpleconsumer - DEBUG - Finalising <pykafka.simpleconsumer.SimpleConsumer at 0x236104d0050 (consumer_group=None)>
2025-03-05 20:13:56,835 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:13:56,835 - pykafka.simpleconsumer - DEBUG - Attempt to cleanup consumer failed
2025-03-05 20:13:56,835 - pykafka.simpleconsumer - ERROR - weakly-referenced object no longer exists
Traceback (most recent call last):
  File "C:\Users\ghier\AppData\Local\Programs\Python\Python311\Lib\site-packages\pykafka\simpleconsumer.py", line 449, in fetcher
    self.cleanup()
    ^^^^^^^^^^^^
ReferenceError: weakly-referenced object no longer exists
2025-03-05 20:13:56,836 - pykafka.simpleconsumer - DEBUG - Fetcher thread exiting
2025-03-05 20:13:56,843 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:13:56,846 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:13:56,847 - pykafka.cluster - INFO - Discovered 1 brokers
2025-03-05 20:13:56,847 - pykafka.cluster - DEBUG - Discovered broker id 1001: b'localhost':9092
2025-03-05 20:13:56,847 - pykafka.connection - DEBUG - Connecting to b'localhost':9092
2025-03-05 20:13:56,849 - pykafka.connection - DEBUG - Successfully connected to b'localhost':9092
2025-03-05 20:13:56,850 - pykafka.cluster - INFO - Discovered 1 topics
2025-03-05 20:13:56,850 - pykafka.cluster - DEBUG - Discovered topic 'b'events''
2025-03-05 20:13:56,851 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:13:56,852 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:13:56,857 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:13:56,857 - pykafka.topic - INFO - Adding 1 partitions
2025-03-05 20:13:56,858 - pykafka.topic - DEBUG - Adding partition b'events'/0
2025-03-05 20:13:56,859 - pykafka.simpleconsumer - INFO - Resetting offsets for 1 partitions
2025-03-05 20:13:56,866 - pykafka.simpleconsumer - INFO - Flushed queue for partition 0
2025-03-05 20:13:56,867 - pykafka.simpleconsumer - INFO - Starting 1 fetcher threads
2025-03-05 20:13:57,849 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:13:57,849 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:13:57,864 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:13:57,880 - basicLogger - INFO - Found 0 player-performance events in Kafka
2025-03-05 20:13:57,881 - pykafka.simpleconsumer - DEBUG - Finalising <pykafka.simpleconsumer.SimpleConsumer at 0x236109197d0 (consumer_group=None)>
2025-03-05 20:13:57,882 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:13:57,882 - pykafka.simpleconsumer - DEBUG - Attempt to cleanup consumer failed
2025-03-05 20:13:57,883 - pykafka.simpleconsumer - ERROR - weakly-referenced object no longer exists
Traceback (most recent call last):
  File "C:\Users\ghier\AppData\Local\Programs\Python\Python311\Lib\site-packages\pykafka\simpleconsumer.py", line 449, in fetcher
    self.cleanup()
    ^^^^^^^^^^^^
ReferenceError: weakly-referenced object no longer exists
2025-03-05 20:13:57,883 - pykafka.simpleconsumer - DEBUG - Fetcher thread exiting
2025-03-05 20:13:57,884 - connexion.validators.parameter - DEBUG - /other-event validating parameters...
2025-03-05 20:13:57,885 - connexion.decorators.parameter - DEBUG - Query Parameter 'index' (sanitized: 'index') in function arguments
2025-03-05 20:13:57,885 - connexion.decorators.parameter - DEBUG - index is a {'name': 'index', 'in': 'query', 'required': True, 'description': 'The index of the audience-interaction event in the Kafka queue.', 'schema': {'type': 'integer', 'example': 0}}
2025-03-05 20:13:57,885 - pykafka.cluster - INFO - Broker version is too old to use automatic API version discovery. Falling back to hardcoded versions list.
2025-03-05 20:13:57,886 - pykafka.cluster - DEBUG - Updating cluster, attempt 1/3
2025-03-05 20:13:57,886 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:13:57,887 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:13:57,891 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:13:57,891 - pykafka.cluster - INFO - Discovered 1 brokers
2025-03-05 20:13:57,892 - pykafka.cluster - DEBUG - Discovered broker id 1001: b'localhost':9092
2025-03-05 20:13:57,893 - pykafka.connection - DEBUG - Connecting to b'localhost':9092
2025-03-05 20:13:57,911 - pykafka.connection - DEBUG - Successfully connected to b'localhost':9092
2025-03-05 20:13:57,912 - pykafka.cluster - INFO - Discovered 1 topics
2025-03-05 20:13:57,912 - pykafka.cluster - DEBUG - Discovered topic 'b'events''
2025-03-05 20:13:57,913 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:13:57,927 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:13:57,931 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:13:57,931 - pykafka.topic - INFO - Adding 1 partitions
2025-03-05 20:13:57,931 - pykafka.topic - DEBUG - Adding partition b'events'/0
2025-03-05 20:13:57,932 - pykafka.simpleconsumer - INFO - Resetting offsets for 1 partitions
2025-03-05 20:13:57,935 - pykafka.simpleconsumer - INFO - Flushed queue for partition 0
2025-03-05 20:13:57,935 - pykafka.simpleconsumer - INFO - Starting 1 fetcher threads
2025-03-05 20:13:58,890 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:13:58,905 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:13:58,936 - basicLogger - INFO - Found 0 audience-interaction events in Kafka
2025-03-05 20:13:58,936 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:13:58,941 - connexion.validators.parameter - DEBUG - /other-event validating parameters...
2025-03-05 20:13:58,943 - connexion.decorators.parameter - DEBUG - Query Parameter 'index' (sanitized: 'index') in function arguments
2025-03-05 20:13:58,943 - connexion.decorators.parameter - DEBUG - index is a {'name': 'index', 'in': 'query', 'required': True, 'description': 'The index of the audience-interaction event in the Kafka queue.', 'schema': {'type': 'integer', 'example': 0}}
2025-03-05 20:13:58,944 - pykafka.cluster - INFO - Broker version is too old to use automatic API version discovery. Falling back to hardcoded versions list.
2025-03-05 20:13:58,945 - pykafka.cluster - DEBUG - Updating cluster, attempt 1/3
2025-03-05 20:13:58,945 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:13:58,946 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:13:58,950 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:13:58,950 - pykafka.simpleconsumer - DEBUG - Finalising <pykafka.simpleconsumer.SimpleConsumer at 0x236104ba750 (consumer_group=None)>
2025-03-05 20:13:58,952 - pykafka.cluster - INFO - Discovered 1 brokers
2025-03-05 20:13:58,953 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:13:58,953 - pykafka.cluster - DEBUG - Discovered broker id 1001: b'localhost':9092
2025-03-05 20:13:58,953 - pykafka.simpleconsumer - DEBUG - Attempt to cleanup consumer failed
2025-03-05 20:13:58,954 - pykafka.connection - DEBUG - Connecting to b'localhost':9092
2025-03-05 20:13:58,954 - pykafka.simpleconsumer - ERROR - weakly-referenced object no longer exists
Traceback (most recent call last):
  File "C:\Users\ghier\AppData\Local\Programs\Python\Python311\Lib\site-packages\pykafka\simpleconsumer.py", line 449, in fetcher
    self.cleanup()
    ^^^^^^^^^^^^
ReferenceError: weakly-referenced object no longer exists
2025-03-05 20:13:58,955 - pykafka.simpleconsumer - DEBUG - Fetcher thread exiting
2025-03-05 20:13:58,955 - pykafka.connection - DEBUG - Successfully connected to b'localhost':9092
2025-03-05 20:13:58,957 - pykafka.cluster - INFO - Discovered 1 topics
2025-03-05 20:13:58,957 - pykafka.cluster - DEBUG - Discovered topic 'b'events''
2025-03-05 20:13:58,958 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:13:58,984 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:13:58,988 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:13:58,989 - pykafka.topic - INFO - Adding 1 partitions
2025-03-05 20:13:58,989 - pykafka.topic - DEBUG - Adding partition b'events'/0
2025-03-05 20:13:58,989 - pykafka.simpleconsumer - INFO - Resetting offsets for 1 partitions
2025-03-05 20:13:58,992 - pykafka.simpleconsumer - INFO - Flushed queue for partition 0
2025-03-05 20:13:58,993 - pykafka.simpleconsumer - INFO - Starting 1 fetcher threads
2025-03-05 20:13:59,963 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:13:59,963 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:13:59,994 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:14:00,012 - pykafka.simpleconsumer - DEBUG - Finalising <pykafka.simpleconsumer.SimpleConsumer at 0x236109188d0 (consumer_group=None)>
2025-03-05 20:14:00,013 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:14:00,013 - basicLogger - INFO - Found 0 audience-interaction events in Kafka
2025-03-05 20:14:00,018 - pykafka.simpleconsumer - DEBUG - Attempt to cleanup consumer failed
2025-03-05 20:14:00,018 - pykafka.simpleconsumer - ERROR - weakly-referenced object no longer exists
Traceback (most recent call last):
  File "C:\Users\ghier\AppData\Local\Programs\Python\Python311\Lib\site-packages\pykafka\simpleconsumer.py", line 449, in fetcher
    self.cleanup()
    ^^^^^^^^^^^^
ReferenceError: weakly-referenced object no longer exists
2025-03-05 20:14:00,020 - connexion.validators.parameter - DEBUG - /stats validating parameters...
2025-03-05 20:14:00,020 - pykafka.simpleconsumer - DEBUG - Fetcher thread exiting
2025-03-05 20:14:00,021 - pykafka.cluster - INFO - Broker version is too old to use automatic API version discovery. Falling back to hardcoded versions list.
2025-03-05 20:14:00,021 - pykafka.cluster - DEBUG - Updating cluster, attempt 1/3
2025-03-05 20:14:00,022 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:14:00,024 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:14:00,032 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:14:00,033 - pykafka.cluster - INFO - Discovered 1 brokers
2025-03-05 20:14:00,033 - pykafka.cluster - DEBUG - Discovered broker id 1001: b'localhost':9092
2025-03-05 20:14:00,034 - pykafka.connection - DEBUG - Connecting to b'localhost':9092
2025-03-05 20:14:00,035 - pykafka.connection - DEBUG - Successfully connected to b'localhost':9092
2025-03-05 20:14:00,038 - pykafka.cluster - INFO - Discovered 1 topics
2025-03-05 20:14:00,038 - pykafka.cluster - DEBUG - Discovered topic 'b'events''
2025-03-05 20:14:00,039 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:14:00,042 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:14:00,049 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:14:00,050 - pykafka.topic - INFO - Adding 1 partitions
2025-03-05 20:14:00,050 - pykafka.topic - DEBUG - Adding partition b'events'/0
2025-03-05 20:14:00,050 - pykafka.simpleconsumer - INFO - Resetting offsets for 1 partitions
2025-03-05 20:14:00,053 - pykafka.simpleconsumer - INFO - Flushed queue for partition 0
2025-03-05 20:14:00,053 - pykafka.simpleconsumer - INFO - Starting 1 fetcher threads
2025-03-05 20:14:01,017 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:14:01,033 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:14:01,063 - basicLogger - INFO - Event stats computed: {'num_player_performance': 0, 'num_audience_interaction': 0}
2025-03-05 20:14:01,063 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:14:01,068 - pykafka.simpleconsumer - DEBUG - Finalising <pykafka.simpleconsumer.SimpleConsumer at 0x236109188d0 (consumer_group=None)>
2025-03-05 20:14:01,068 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:14:01,068 - pykafka.simpleconsumer - DEBUG - Attempt to cleanup consumer failed
2025-03-05 20:14:01,070 - pykafka.simpleconsumer - ERROR - weakly-referenced object no longer exists
Traceback (most recent call last):
  File "C:\Users\ghier\AppData\Local\Programs\Python\Python311\Lib\site-packages\pykafka\simpleconsumer.py", line 449, in fetcher
    self.cleanup()
    ^^^^^^^^^^^^
ReferenceError: weakly-referenced object no longer exists
2025-03-05 20:14:01,070 - pykafka.simpleconsumer - DEBUG - Fetcher thread exiting
2025-03-05 20:14:02,083 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:16:21,273 - connexion.middleware.main - WARNING - `ConnexionMiddleware.run` is optimized for development. For production, run using a dedicated ASGI server.
2025-03-05 20:16:21,278 - asyncio - DEBUG - Using proactor: IocpProactor
2025-03-05 20:16:21,328 - connexion.middleware.abstract - DEBUG - Adding /my-first-event...
2025-03-05 20:16:21,348 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:16:21,349 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:16:21,349 - connexion.middleware.abstract - DEBUG - Adding /other-event...
2025-03-05 20:16:21,349 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:16:21,349 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:16:21,349 - connexion.middleware.abstract - DEBUG - Adding /stats...
2025-03-05 20:16:21,349 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:16:21,349 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:16:21,350 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:16:21,351 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:16:21,351 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:16:21,351 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:16:21,351 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:16:21,351 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:16:21,352 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:16:21,352 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:16:21,352 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:16:21,352 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:16:21,352 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:16:21,353 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:16:21,353 - connexion.middleware.validation - DEBUG - Strict Request Validation: True
2025-03-05 20:16:21,353 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:16:21,353 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:16:21,354 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:16:21,354 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:16:21,354 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:16:21,354 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:16:21,355 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:16:21,355 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:16:21,355 - connexion.middleware.security - DEBUG - ... Security: None
2025-03-05 20:16:21,355 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:16:21,356 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:16:21,356 - connexion.middleware.security - DEBUG - ... Security: None
2025-03-05 20:16:21,356 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:16:21,356 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:16:21,357 - connexion.middleware.security - DEBUG - ... Security: None
2025-03-05 20:16:21,357 - connexion.middleware.abstract - DEBUG - Adding /my-first-event...
2025-03-05 20:16:21,357 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:16:21,358 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:16:21,358 - connexion.middleware.abstract - DEBUG - Adding /other-event...
2025-03-05 20:16:21,358 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:16:21,359 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:16:21,359 - connexion.middleware.abstract - DEBUG - Adding /stats...
2025-03-05 20:16:21,359 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:16:21,359 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:16:21,360 - connexion.middleware.swagger_ui - INFO - Adding spec json: /openapi.json
2025-03-05 20:16:21,360 - connexion.middleware.swagger_ui - DEBUG - Adding spec yaml: //openapi.yaml
2025-03-05 20:16:21,360 - connexion.middleware.swagger_ui - DEBUG - Adding swagger-ui: /ui/
2025-03-05 20:16:35,727 - connexion.validators.parameter - DEBUG - /my-first-event validating parameters...
2025-03-05 20:16:35,730 - connexion.decorators.parameter - DEBUG - Query Parameter 'index' (sanitized: 'index') in function arguments
2025-03-05 20:16:35,730 - connexion.decorators.parameter - DEBUG - index is a {'name': 'index', 'in': 'query', 'required': True, 'description': 'The index of the player-performance event in the Kafka queue.', 'schema': {'type': 'integer', 'example': 0}}
2025-03-05 20:16:35,731 - pykafka.cluster - INFO - Broker version is too old to use automatic API version discovery. Falling back to hardcoded versions list.
2025-03-05 20:16:35,732 - pykafka.cluster - DEBUG - Updating cluster, attempt 1/3
2025-03-05 20:16:35,732 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:16:35,740 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:16:35,767 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:16:35,767 - pykafka.cluster - INFO - Discovered 1 brokers
2025-03-05 20:16:35,767 - pykafka.cluster - DEBUG - Discovered broker id 1001: b'localhost':9092
2025-03-05 20:16:35,768 - pykafka.connection - DEBUG - Connecting to b'localhost':9092
2025-03-05 20:16:35,769 - pykafka.connection - DEBUG - Successfully connected to b'localhost':9092
2025-03-05 20:16:35,770 - pykafka.cluster - INFO - Discovered 1 topics
2025-03-05 20:16:35,770 - pykafka.cluster - DEBUG - Discovered topic 'b'events''
2025-03-05 20:16:35,773 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:16:35,774 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:16:35,782 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:16:35,782 - pykafka.topic - INFO - Adding 1 partitions
2025-03-05 20:16:35,783 - pykafka.topic - DEBUG - Adding partition b'events'/0
2025-03-05 20:16:35,783 - pykafka.simpleconsumer - INFO - Resetting offsets for 1 partitions
2025-03-05 20:16:35,798 - pykafka.simpleconsumer - INFO - Flushed queue for partition 0
2025-03-05 20:16:35,799 - pykafka.simpleconsumer - INFO - Starting 1 fetcher threads
2025-03-05 20:16:36,774 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:16:36,789 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:16:36,804 - basicLogger - INFO - Found 0 player-performance events in Kafka
2025-03-05 20:16:36,809 - connexion.validators.parameter - DEBUG - /my-first-event validating parameters...
2025-03-05 20:16:36,811 - connexion.decorators.parameter - DEBUG - Query Parameter 'index' (sanitized: 'index') in function arguments
2025-03-05 20:16:36,811 - connexion.decorators.parameter - DEBUG - index is a {'name': 'index', 'in': 'query', 'required': True, 'description': 'The index of the player-performance event in the Kafka queue.', 'schema': {'type': 'integer', 'example': 0}}
2025-03-05 20:16:36,811 - pykafka.cluster - INFO - Broker version is too old to use automatic API version discovery. Falling back to hardcoded versions list.
2025-03-05 20:16:36,812 - pykafka.cluster - DEBUG - Updating cluster, attempt 1/3
2025-03-05 20:16:36,812 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:16:36,814 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:16:36,819 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:16:36,820 - pykafka.cluster - INFO - Discovered 1 brokers
2025-03-05 20:16:36,820 - pykafka.cluster - DEBUG - Discovered broker id 1001: b'localhost':9092
2025-03-05 20:16:36,821 - pykafka.connection - DEBUG - Connecting to b'localhost':9092
2025-03-05 20:16:36,835 - pykafka.connection - DEBUG - Successfully connected to b'localhost':9092
2025-03-05 20:16:36,836 - pykafka.cluster - INFO - Discovered 1 topics
2025-03-05 20:16:36,836 - pykafka.cluster - DEBUG - Discovered topic 'b'events''
2025-03-05 20:16:36,837 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:16:36,850 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:16:36,854 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:16:36,855 - pykafka.topic - INFO - Adding 1 partitions
2025-03-05 20:16:36,855 - pykafka.topic - DEBUG - Adding partition b'events'/0
2025-03-05 20:16:36,855 - pykafka.simpleconsumer - DEBUG - Finalising <pykafka.simpleconsumer.SimpleConsumer at 0x133cb4c3390 (consumer_group=None)>
2025-03-05 20:16:36,856 - pykafka.simpleconsumer - INFO - Resetting offsets for 1 partitions
2025-03-05 20:16:36,856 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:16:36,857 - pykafka.simpleconsumer - DEBUG - Attempt to cleanup consumer failed
2025-03-05 20:16:36,857 - pykafka.simpleconsumer - ERROR - weakly-referenced object no longer exists
Traceback (most recent call last):
  File "C:\Users\ghier\AppData\Local\Programs\Python\Python311\Lib\site-packages\pykafka\simpleconsumer.py", line 449, in fetcher
    self.cleanup()
    ^^^^^^^^^^^^
ReferenceError: weakly-referenced object no longer exists
2025-03-05 20:16:36,859 - pykafka.simpleconsumer - DEBUG - Fetcher thread exiting
2025-03-05 20:16:36,859 - pykafka.simpleconsumer - INFO - Flushed queue for partition 0
2025-03-05 20:16:36,860 - pykafka.simpleconsumer - INFO - Starting 1 fetcher threads
2025-03-05 20:16:37,827 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:16:37,858 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:16:37,858 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:16:37,873 - basicLogger - INFO - Found 0 player-performance events in Kafka
2025-03-05 20:16:37,877 - connexion.validators.parameter - DEBUG - /other-event validating parameters...
2025-03-05 20:16:37,878 - connexion.decorators.parameter - DEBUG - Query Parameter 'index' (sanitized: 'index') in function arguments
2025-03-05 20:16:37,878 - pykafka.simpleconsumer - DEBUG - Finalising <pykafka.simpleconsumer.SimpleConsumer at 0x133cb925d50 (consumer_group=None)>
2025-03-05 20:16:37,879 - connexion.decorators.parameter - DEBUG - index is a {'name': 'index', 'in': 'query', 'required': True, 'description': 'The index of the audience-interaction event in the Kafka queue.', 'schema': {'type': 'integer', 'example': 0}}
2025-03-05 20:16:37,879 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:16:37,879 - pykafka.cluster - INFO - Broker version is too old to use automatic API version discovery. Falling back to hardcoded versions list.
2025-03-05 20:16:37,880 - pykafka.simpleconsumer - DEBUG - Attempt to cleanup consumer failed
2025-03-05 20:16:37,880 - pykafka.cluster - DEBUG - Updating cluster, attempt 1/3
2025-03-05 20:16:37,880 - pykafka.simpleconsumer - ERROR - weakly-referenced object no longer exists
Traceback (most recent call last):
  File "C:\Users\ghier\AppData\Local\Programs\Python\Python311\Lib\site-packages\pykafka\simpleconsumer.py", line 449, in fetcher
    self.cleanup()
    ^^^^^^^^^^^^
ReferenceError: weakly-referenced object no longer exists
2025-03-05 20:16:37,881 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:16:37,881 - pykafka.simpleconsumer - DEBUG - Fetcher thread exiting
2025-03-05 20:16:37,883 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:16:37,888 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:16:37,888 - pykafka.cluster - INFO - Discovered 1 brokers
2025-03-05 20:16:37,888 - pykafka.cluster - DEBUG - Discovered broker id 1001: b'localhost':9092
2025-03-05 20:16:37,889 - pykafka.connection - DEBUG - Connecting to b'localhost':9092
2025-03-05 20:16:37,890 - pykafka.connection - DEBUG - Successfully connected to b'localhost':9092
2025-03-05 20:16:37,890 - pykafka.cluster - INFO - Discovered 1 topics
2025-03-05 20:16:37,891 - pykafka.cluster - DEBUG - Discovered topic 'b'events''
2025-03-05 20:16:37,891 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:16:37,905 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:16:37,909 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:16:37,909 - pykafka.topic - INFO - Adding 1 partitions
2025-03-05 20:16:37,909 - pykafka.topic - DEBUG - Adding partition b'events'/0
2025-03-05 20:16:37,910 - pykafka.simpleconsumer - INFO - Resetting offsets for 1 partitions
2025-03-05 20:16:37,912 - pykafka.simpleconsumer - INFO - Flushed queue for partition 0
2025-03-05 20:16:37,912 - pykafka.simpleconsumer - INFO - Starting 1 fetcher threads
2025-03-05 20:16:38,884 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:16:38,899 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:16:38,915 - basicLogger - INFO - Found 0 audience-interaction events in Kafka
2025-03-05 20:16:38,915 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:16:38,919 - connexion.validators.parameter - DEBUG - /other-event validating parameters...
2025-03-05 20:16:38,920 - connexion.decorators.parameter - DEBUG - Query Parameter 'index' (sanitized: 'index') in function arguments
2025-03-05 20:16:38,920 - connexion.decorators.parameter - DEBUG - index is a {'name': 'index', 'in': 'query', 'required': True, 'description': 'The index of the audience-interaction event in the Kafka queue.', 'schema': {'type': 'integer', 'example': 0}}
2025-03-05 20:16:38,921 - pykafka.cluster - INFO - Broker version is too old to use automatic API version discovery. Falling back to hardcoded versions list.
2025-03-05 20:16:38,921 - pykafka.cluster - DEBUG - Updating cluster, attempt 1/3
2025-03-05 20:16:38,921 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:16:38,944 - pykafka.simpleconsumer - DEBUG - Finalising <pykafka.simpleconsumer.SimpleConsumer at 0x133cb91f810 (consumer_group=None)>
2025-03-05 20:16:38,944 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:16:38,944 - pykafka.simpleconsumer - DEBUG - Attempt to cleanup consumer failed
2025-03-05 20:16:38,945 - pykafka.simpleconsumer - ERROR - weakly-referenced object no longer exists
Traceback (most recent call last):
  File "C:\Users\ghier\AppData\Local\Programs\Python\Python311\Lib\site-packages\pykafka\simpleconsumer.py", line 449, in fetcher
    self.cleanup()
    ^^^^^^^^^^^^
ReferenceError: weakly-referenced object no longer exists
2025-03-05 20:16:38,945 - pykafka.simpleconsumer - DEBUG - Fetcher thread exiting
2025-03-05 20:16:38,947 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:16:38,949 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:16:38,950 - pykafka.cluster - INFO - Discovered 1 brokers
2025-03-05 20:16:38,950 - pykafka.cluster - DEBUG - Discovered broker id 1001: b'localhost':9092
2025-03-05 20:16:38,951 - pykafka.connection - DEBUG - Connecting to b'localhost':9092
2025-03-05 20:16:38,954 - pykafka.connection - DEBUG - Successfully connected to b'localhost':9092
2025-03-05 20:16:38,955 - pykafka.cluster - INFO - Discovered 1 topics
2025-03-05 20:16:38,956 - pykafka.cluster - DEBUG - Discovered topic 'b'events''
2025-03-05 20:16:38,956 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:16:38,977 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:16:38,981 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:16:38,981 - pykafka.topic - INFO - Adding 1 partitions
2025-03-05 20:16:38,981 - pykafka.topic - DEBUG - Adding partition b'events'/0
2025-03-05 20:16:38,982 - pykafka.simpleconsumer - INFO - Resetting offsets for 1 partitions
2025-03-05 20:16:38,984 - pykafka.simpleconsumer - INFO - Flushed queue for partition 0
2025-03-05 20:16:38,985 - pykafka.simpleconsumer - INFO - Starting 1 fetcher threads
2025-03-05 20:16:39,943 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:16:39,958 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:16:39,989 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:16:39,989 - basicLogger - INFO - Found 0 audience-interaction events in Kafka
2025-03-05 20:16:39,996 - connexion.validators.parameter - DEBUG - /stats validating parameters...
2025-03-05 20:16:39,997 - pykafka.cluster - INFO - Broker version is too old to use automatic API version discovery. Falling back to hardcoded versions list.
2025-03-05 20:16:39,997 - pykafka.cluster - DEBUG - Updating cluster, attempt 1/3
2025-03-05 20:16:39,998 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:16:39,999 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:16:40,004 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:16:40,004 - pykafka.cluster - INFO - Discovered 1 brokers
2025-03-05 20:16:40,004 - pykafka.cluster - DEBUG - Discovered broker id 1001: b'localhost':9092
2025-03-05 20:16:40,006 - pykafka.connection - DEBUG - Connecting to b'localhost':9092
2025-03-05 20:16:40,017 - pykafka.simpleconsumer - DEBUG - Finalising <pykafka.simpleconsumer.SimpleConsumer at 0x133cb7320d0 (consumer_group=None)>
2025-03-05 20:16:40,017 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:16:40,018 - pykafka.simpleconsumer - DEBUG - Attempt to cleanup consumer failed
2025-03-05 20:16:40,019 - pykafka.simpleconsumer - ERROR - weakly-referenced object no longer exists
Traceback (most recent call last):
  File "C:\Users\ghier\AppData\Local\Programs\Python\Python311\Lib\site-packages\pykafka\simpleconsumer.py", line 449, in fetcher
    self.cleanup()
    ^^^^^^^^^^^^
ReferenceError: weakly-referenced object no longer exists
2025-03-05 20:16:40,019 - pykafka.simpleconsumer - DEBUG - Fetcher thread exiting
2025-03-05 20:16:40,020 - pykafka.connection - DEBUG - Successfully connected to b'localhost':9092
2025-03-05 20:16:40,020 - pykafka.cluster - INFO - Discovered 1 topics
2025-03-05 20:16:40,021 - pykafka.cluster - DEBUG - Discovered topic 'b'events''
2025-03-05 20:16:40,021 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:16:40,035 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:16:40,038 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:16:40,038 - pykafka.topic - INFO - Adding 1 partitions
2025-03-05 20:16:40,039 - pykafka.topic - DEBUG - Adding partition b'events'/0
2025-03-05 20:16:40,039 - pykafka.simpleconsumer - INFO - Resetting offsets for 1 partitions
2025-03-05 20:16:40,041 - pykafka.simpleconsumer - INFO - Flushed queue for partition 0
2025-03-05 20:16:40,042 - pykafka.simpleconsumer - INFO - Starting 1 fetcher threads
2025-03-05 20:16:41,011 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:16:41,028 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:16:41,043 - basicLogger - INFO - Event stats computed: {'num_player_performance': 0, 'num_audience_interaction': 0}
2025-03-05 20:16:41,043 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:16:41,073 - pykafka.simpleconsumer - DEBUG - Finalising <pykafka.simpleconsumer.SimpleConsumer at 0x133cb747410 (consumer_group=None)>
2025-03-05 20:16:41,074 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:16:41,075 - pykafka.simpleconsumer - DEBUG - Attempt to cleanup consumer failed
2025-03-05 20:16:41,075 - pykafka.simpleconsumer - ERROR - weakly-referenced object no longer exists
Traceback (most recent call last):
  File "C:\Users\ghier\AppData\Local\Programs\Python\Python311\Lib\site-packages\pykafka\simpleconsumer.py", line 449, in fetcher
    self.cleanup()
    ^^^^^^^^^^^^
ReferenceError: weakly-referenced object no longer exists
2025-03-05 20:16:41,076 - pykafka.simpleconsumer - DEBUG - Fetcher thread exiting
2025-03-05 20:16:42,086 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:22:12,887 - connexion.middleware.main - WARNING - `ConnexionMiddleware.run` is optimized for development. For production, run using a dedicated ASGI server.
2025-03-05 20:22:12,890 - asyncio - DEBUG - Using proactor: IocpProactor
2025-03-05 20:22:12,956 - connexion.middleware.abstract - DEBUG - Adding /my-first-event...
2025-03-05 20:22:12,991 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:22:12,991 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:22:12,991 - connexion.middleware.abstract - DEBUG - Adding /other-event...
2025-03-05 20:22:12,992 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:22:12,992 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:22:12,992 - connexion.middleware.abstract - DEBUG - Adding /stats...
2025-03-05 20:22:12,993 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:22:12,993 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:22:12,995 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:22:12,995 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:22:12,995 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:22:12,996 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:22:12,996 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:22:12,996 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:22:12,996 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:22:12,996 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:22:12,998 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:22:12,998 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:22:12,998 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:22:12,998 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:22:12,999 - connexion.middleware.validation - DEBUG - Strict Request Validation: True
2025-03-05 20:22:13,000 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:22:13,001 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:22:13,001 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:22:13,002 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:22:13,004 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:22:13,004 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:22:13,005 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:22:13,006 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:22:13,008 - connexion.middleware.security - DEBUG - ... Security: None
2025-03-05 20:22:13,010 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:22:13,012 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:22:13,015 - connexion.middleware.security - DEBUG - ... Security: None
2025-03-05 20:22:13,015 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:22:13,016 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:22:13,017 - connexion.middleware.security - DEBUG - ... Security: None
2025-03-05 20:22:13,017 - connexion.middleware.abstract - DEBUG - Adding /my-first-event...
2025-03-05 20:22:13,019 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:22:13,020 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:22:13,020 - connexion.middleware.abstract - DEBUG - Adding /other-event...
2025-03-05 20:22:13,021 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:22:13,022 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:22:13,023 - connexion.middleware.abstract - DEBUG - Adding /stats...
2025-03-05 20:22:13,023 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:22:13,023 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:22:13,025 - connexion.middleware.swagger_ui - INFO - Adding spec json: /openapi.json
2025-03-05 20:22:13,025 - connexion.middleware.swagger_ui - DEBUG - Adding spec yaml: //openapi.yaml
2025-03-05 20:22:13,027 - connexion.middleware.swagger_ui - DEBUG - Adding swagger-ui: /ui/
2025-03-05 20:22:15,994 - connexion.validators.parameter - DEBUG - /my-first-event validating parameters...
2025-03-05 20:22:15,998 - connexion.decorators.parameter - DEBUG - Query Parameter 'index' (sanitized: 'index') in function arguments
2025-03-05 20:22:15,998 - connexion.decorators.parameter - DEBUG - index is a {'name': 'index', 'in': 'query', 'required': True, 'description': 'The index of the player-performance event in the Kafka queue.', 'schema': {'type': 'integer', 'example': 0}}
2025-03-05 20:22:15,999 - pykafka.cluster - INFO - Broker version is too old to use automatic API version discovery. Falling back to hardcoded versions list.
2025-03-05 20:22:15,999 - pykafka.cluster - DEBUG - Updating cluster, attempt 1/3
2025-03-05 20:22:16,000 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:22:16,008 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:22:16,016 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:22:16,017 - pykafka.cluster - INFO - Discovered 1 brokers
2025-03-05 20:22:16,017 - pykafka.cluster - DEBUG - Discovered broker id 1001: b'localhost':9092
2025-03-05 20:22:16,018 - pykafka.connection - DEBUG - Connecting to b'localhost':9092
2025-03-05 20:22:16,019 - pykafka.connection - DEBUG - Successfully connected to b'localhost':9092
2025-03-05 20:22:16,020 - pykafka.cluster - INFO - Discovered 1 topics
2025-03-05 20:22:16,020 - pykafka.cluster - DEBUG - Discovered topic 'b'events''
2025-03-05 20:22:16,022 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:22:16,023 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:22:16,028 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:22:16,028 - pykafka.topic - INFO - Adding 1 partitions
2025-03-05 20:22:16,028 - pykafka.topic - DEBUG - Adding partition b'events'/0
2025-03-05 20:22:16,030 - pykafka.simpleconsumer - INFO - Resetting offsets for 1 partitions
2025-03-05 20:22:16,034 - pykafka.simpleconsumer - INFO - Flushed queue for partition 0
2025-03-05 20:22:16,034 - pykafka.simpleconsumer - INFO - Starting 1 fetcher threads
2025-03-05 20:22:17,027 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:22:17,042 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:22:17,042 - basicLogger - INFO - Found 0 player-performance events in Kafka
2025-03-05 20:22:17,048 - connexion.validators.parameter - DEBUG - /my-first-event validating parameters...
2025-03-05 20:22:17,050 - connexion.decorators.parameter - DEBUG - Query Parameter 'index' (sanitized: 'index') in function arguments
2025-03-05 20:22:17,050 - connexion.decorators.parameter - DEBUG - index is a {'name': 'index', 'in': 'query', 'required': True, 'description': 'The index of the player-performance event in the Kafka queue.', 'schema': {'type': 'integer', 'example': 0}}
2025-03-05 20:22:17,050 - pykafka.cluster - INFO - Broker version is too old to use automatic API version discovery. Falling back to hardcoded versions list.
2025-03-05 20:22:17,051 - pykafka.cluster - DEBUG - Updating cluster, attempt 1/3
2025-03-05 20:22:17,052 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:22:17,053 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:22:17,059 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:22:17,060 - pykafka.cluster - INFO - Discovered 1 brokers
2025-03-05 20:22:17,060 - pykafka.cluster - DEBUG - Discovered broker id 1001: b'localhost':9092
2025-03-05 20:22:17,061 - pykafka.connection - DEBUG - Connecting to b'localhost':9092
2025-03-05 20:22:17,063 - pykafka.connection - DEBUG - Successfully connected to b'localhost':9092
2025-03-05 20:22:17,064 - pykafka.cluster - INFO - Discovered 1 topics
2025-03-05 20:22:17,065 - pykafka.cluster - DEBUG - Discovered topic 'b'events''
2025-03-05 20:22:17,065 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:22:17,066 - pykafka.simpleconsumer - DEBUG - Finalising <pykafka.simpleconsumer.SimpleConsumer at 0x21fad073350 (consumer_group=None)>
2025-03-05 20:22:17,066 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:22:17,067 - pykafka.simpleconsumer - DEBUG - Attempt to cleanup consumer failed
2025-03-05 20:22:17,067 - pykafka.simpleconsumer - ERROR - weakly-referenced object no longer exists
Traceback (most recent call last):
  File "C:\Users\ghier\AppData\Local\Programs\Python\Python311\Lib\site-packages\pykafka\simpleconsumer.py", line 449, in fetcher
    self.cleanup()
    ^^^^^^^^^^^^
ReferenceError: weakly-referenced object no longer exists
2025-03-05 20:22:17,068 - pykafka.simpleconsumer - DEBUG - Fetcher thread exiting
2025-03-05 20:22:17,088 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:22:17,092 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:22:17,093 - pykafka.topic - INFO - Adding 1 partitions
2025-03-05 20:22:17,093 - pykafka.topic - DEBUG - Adding partition b'events'/0
2025-03-05 20:22:17,093 - pykafka.simpleconsumer - INFO - Resetting offsets for 1 partitions
2025-03-05 20:22:17,096 - pykafka.simpleconsumer - INFO - Flushed queue for partition 0
2025-03-05 20:22:17,097 - pykafka.simpleconsumer - INFO - Starting 1 fetcher threads
2025-03-05 20:22:18,071 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:22:18,071 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:22:18,101 - basicLogger - INFO - Found 0 player-performance events in Kafka
2025-03-05 20:22:18,101 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:22:18,104 - connexion.validators.parameter - DEBUG - /other-event validating parameters...
2025-03-05 20:22:18,105 - connexion.decorators.parameter - DEBUG - Query Parameter 'index' (sanitized: 'index') in function arguments
2025-03-05 20:22:18,106 - connexion.decorators.parameter - DEBUG - index is a {'name': 'index', 'in': 'query', 'required': True, 'description': 'The index of the audience-interaction event in the Kafka queue.', 'schema': {'type': 'integer', 'example': 0}}
2025-03-05 20:22:18,106 - pykafka.cluster - INFO - Broker version is too old to use automatic API version discovery. Falling back to hardcoded versions list.
2025-03-05 20:22:18,106 - pykafka.cluster - DEBUG - Updating cluster, attempt 1/3
2025-03-05 20:22:18,107 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:22:18,112 - pykafka.simpleconsumer - DEBUG - Finalising <pykafka.simpleconsumer.SimpleConsumer at 0x21fac981290 (consumer_group=None)>
2025-03-05 20:22:18,112 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:22:18,112 - pykafka.simpleconsumer - DEBUG - Attempt to cleanup consumer failed
2025-03-05 20:22:18,112 - pykafka.simpleconsumer - ERROR - weakly-referenced object no longer exists
Traceback (most recent call last):
  File "C:\Users\ghier\AppData\Local\Programs\Python\Python311\Lib\site-packages\pykafka\simpleconsumer.py", line 449, in fetcher
    self.cleanup()
    ^^^^^^^^^^^^
ReferenceError: weakly-referenced object no longer exists
2025-03-05 20:22:18,113 - pykafka.simpleconsumer - DEBUG - Fetcher thread exiting
2025-03-05 20:22:18,132 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:22:18,135 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:22:18,136 - pykafka.cluster - INFO - Discovered 1 brokers
2025-03-05 20:22:18,136 - pykafka.cluster - DEBUG - Discovered broker id 1001: b'localhost':9092
2025-03-05 20:22:18,136 - pykafka.connection - DEBUG - Connecting to b'localhost':9092
2025-03-05 20:22:18,148 - pykafka.connection - DEBUG - Successfully connected to b'localhost':9092
2025-03-05 20:22:18,148 - pykafka.cluster - INFO - Discovered 1 topics
2025-03-05 20:22:18,148 - pykafka.cluster - DEBUG - Discovered topic 'b'events''
2025-03-05 20:22:18,150 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:22:18,151 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:22:18,155 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:22:18,155 - pykafka.topic - INFO - Adding 1 partitions
2025-03-05 20:22:18,156 - pykafka.topic - DEBUG - Adding partition b'events'/0
2025-03-05 20:22:18,156 - pykafka.simpleconsumer - INFO - Resetting offsets for 1 partitions
2025-03-05 20:22:18,159 - pykafka.simpleconsumer - INFO - Flushed queue for partition 0
2025-03-05 20:22:18,159 - pykafka.simpleconsumer - INFO - Starting 1 fetcher threads
2025-03-05 20:22:19,126 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:22:19,142 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:22:19,157 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:22:19,174 - basicLogger - INFO - Found 0 audience-interaction events in Kafka
2025-03-05 20:22:19,179 - connexion.validators.parameter - DEBUG - /other-event validating parameters...
2025-03-05 20:22:19,180 - connexion.decorators.parameter - DEBUG - Query Parameter 'index' (sanitized: 'index') in function arguments
2025-03-05 20:22:19,180 - connexion.decorators.parameter - DEBUG - index is a {'name': 'index', 'in': 'query', 'required': True, 'description': 'The index of the audience-interaction event in the Kafka queue.', 'schema': {'type': 'integer', 'example': 0}}
2025-03-05 20:22:19,181 - pykafka.cluster - INFO - Broker version is too old to use automatic API version discovery. Falling back to hardcoded versions list.
2025-03-05 20:22:19,181 - pykafka.cluster - DEBUG - Updating cluster, attempt 1/3
2025-03-05 20:22:19,182 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:22:19,184 - pykafka.simpleconsumer - DEBUG - Finalising <pykafka.simpleconsumer.SimpleConsumer at 0x21fad468350 (consumer_group=None)>
2025-03-05 20:22:19,184 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:22:19,185 - pykafka.simpleconsumer - DEBUG - Attempt to cleanup consumer failed
2025-03-05 20:22:19,185 - pykafka.simpleconsumer - ERROR - weakly-referenced object no longer exists
Traceback (most recent call last):
  File "C:\Users\ghier\AppData\Local\Programs\Python\Python311\Lib\site-packages\pykafka\simpleconsumer.py", line 449, in fetcher
    self.cleanup()
    ^^^^^^^^^^^^
ReferenceError: weakly-referenced object no longer exists
2025-03-05 20:22:19,186 - pykafka.simpleconsumer - DEBUG - Fetcher thread exiting
2025-03-05 20:22:19,204 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:22:19,208 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:22:19,208 - pykafka.cluster - INFO - Discovered 1 brokers
2025-03-05 20:22:19,208 - pykafka.cluster - DEBUG - Discovered broker id 1001: b'localhost':9092
2025-03-05 20:22:19,209 - pykafka.connection - DEBUG - Connecting to b'localhost':9092
2025-03-05 20:22:19,210 - pykafka.connection - DEBUG - Successfully connected to b'localhost':9092
2025-03-05 20:22:19,213 - pykafka.cluster - INFO - Discovered 1 topics
2025-03-05 20:22:19,214 - pykafka.cluster - DEBUG - Discovered topic 'b'events''
2025-03-05 20:22:19,215 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:22:19,235 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:22:19,237 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:22:19,238 - pykafka.topic - INFO - Adding 1 partitions
2025-03-05 20:22:19,238 - pykafka.topic - DEBUG - Adding partition b'events'/0
2025-03-05 20:22:19,238 - pykafka.simpleconsumer - INFO - Resetting offsets for 1 partitions
2025-03-05 20:22:19,241 - pykafka.simpleconsumer - INFO - Flushed queue for partition 0
2025-03-05 20:22:19,241 - pykafka.simpleconsumer - INFO - Starting 1 fetcher threads
2025-03-05 20:22:20,186 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:22:20,217 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:22:20,249 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:22:20,249 - basicLogger - INFO - Found 0 audience-interaction events in Kafka
2025-03-05 20:22:20,254 - connexion.validators.parameter - DEBUG - /stats validating parameters...
2025-03-05 20:22:20,255 - pykafka.cluster - INFO - Broker version is too old to use automatic API version discovery. Falling back to hardcoded versions list.
2025-03-05 20:22:20,255 - pykafka.cluster - DEBUG - Updating cluster, attempt 1/3
2025-03-05 20:22:20,256 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:22:20,257 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:22:20,260 - pykafka.simpleconsumer - DEBUG - Finalising <pykafka.simpleconsumer.SimpleConsumer at 0x21fad47b610 (consumer_group=None)>
2025-03-05 20:22:20,260 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:22:20,261 - pykafka.simpleconsumer - DEBUG - Attempt to cleanup consumer failed
2025-03-05 20:22:20,262 - pykafka.simpleconsumer - ERROR - weakly-referenced object no longer exists
Traceback (most recent call last):
  File "C:\Users\ghier\AppData\Local\Programs\Python\Python311\Lib\site-packages\pykafka\simpleconsumer.py", line 449, in fetcher
    self.cleanup()
    ^^^^^^^^^^^^
ReferenceError: weakly-referenced object no longer exists
2025-03-05 20:22:20,263 - pykafka.simpleconsumer - DEBUG - Fetcher thread exiting
2025-03-05 20:22:20,266 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:22:20,267 - pykafka.cluster - INFO - Discovered 1 brokers
2025-03-05 20:22:20,267 - pykafka.cluster - DEBUG - Discovered broker id 1001: b'localhost':9092
2025-03-05 20:22:20,267 - pykafka.connection - DEBUG - Connecting to b'localhost':9092
2025-03-05 20:22:20,268 - pykafka.connection - DEBUG - Successfully connected to b'localhost':9092
2025-03-05 20:22:20,271 - pykafka.cluster - INFO - Discovered 1 topics
2025-03-05 20:22:20,271 - pykafka.cluster - DEBUG - Discovered topic 'b'events''
2025-03-05 20:22:20,272 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:22:20,273 - pykafka.connection - DEBUG - Successfully connected to localhost:9092
2025-03-05 20:22:20,280 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:22:20,280 - pykafka.topic - INFO - Adding 1 partitions
2025-03-05 20:22:20,281 - pykafka.topic - DEBUG - Adding partition b'events'/0
2025-03-05 20:22:20,281 - pykafka.simpleconsumer - INFO - Resetting offsets for 1 partitions
2025-03-05 20:22:20,285 - pykafka.simpleconsumer - INFO - Flushed queue for partition 0
2025-03-05 20:22:20,285 - pykafka.simpleconsumer - INFO - Starting 1 fetcher threads
2025-03-05 20:22:21,275 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:22:21,275 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:22:21,291 - basicLogger - INFO - Event stats computed: {'num_player_performance': 0, 'num_audience_interaction': 0}
2025-03-05 20:22:21,291 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:22:21,298 - pykafka.simpleconsumer - DEBUG - Finalising <pykafka.simpleconsumer.SimpleConsumer at 0x21fad466a50 (consumer_group=None)>
2025-03-05 20:22:21,298 - pykafka.handlers - INFO - RequestHandler.stop: about to flush requests queue
2025-03-05 20:22:21,298 - pykafka.simpleconsumer - DEBUG - Attempt to cleanup consumer failed
2025-03-05 20:22:21,301 - pykafka.simpleconsumer - ERROR - weakly-referenced object no longer exists
Traceback (most recent call last):
  File "C:\Users\ghier\AppData\Local\Programs\Python\Python311\Lib\site-packages\pykafka\simpleconsumer.py", line 449, in fetcher
    self.cleanup()
    ^^^^^^^^^^^^
ReferenceError: weakly-referenced object no longer exists
2025-03-05 20:22:21,302 - pykafka.simpleconsumer - DEBUG - Fetcher thread exiting
2025-03-05 20:22:22,298 - pykafka.handlers - INFO - RequestHandler worker: exiting cleanly
2025-03-05 20:29:51,394 - connexion.middleware.main - WARNING - `ConnexionMiddleware.run` is optimized for development. For production, run using a dedicated ASGI server.
2025-03-05 20:29:51,399 - asyncio - DEBUG - Using proactor: IocpProactor
2025-03-05 20:29:51,481 - connexion.middleware.abstract - DEBUG - Adding /my-first-event...
2025-03-05 20:29:51,521 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:29:51,522 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:29:51,522 - connexion.middleware.abstract - DEBUG - Adding /other-event...
2025-03-05 20:29:51,522 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:29:51,523 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:29:51,523 - connexion.middleware.abstract - DEBUG - Adding /stats...
2025-03-05 20:29:51,523 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:29:51,523 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:29:51,525 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:29:51,525 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:29:51,525 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:29:51,526 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:29:51,526 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:29:51,526 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:29:51,527 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:29:51,527 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:29:51,527 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:29:51,528 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:29:51,528 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:29:51,528 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:29:51,528 - connexion.middleware.validation - DEBUG - Strict Request Validation: True
2025-03-05 20:29:51,529 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:29:51,529 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:29:51,530 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:29:51,530 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:29:51,531 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:29:51,531 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:29:51,532 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:29:51,532 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:29:51,532 - connexion.middleware.security - DEBUG - ... Security: None
2025-03-05 20:29:51,534 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:29:51,534 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:29:51,534 - connexion.middleware.security - DEBUG - ... Security: None
2025-03-05 20:29:51,535 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:29:51,535 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:29:51,535 - connexion.middleware.security - DEBUG - ... Security: None
2025-03-05 20:29:51,536 - connexion.middleware.abstract - DEBUG - Adding /my-first-event...
2025-03-05 20:29:51,536 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:29:51,536 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:29:51,537 - connexion.middleware.abstract - DEBUG - Adding /other-event...
2025-03-05 20:29:51,538 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:29:51,538 - connexion.operations.openapi3 - DEBUG - produces: ['application/json', 'application/json']
2025-03-05 20:29:51,540 - connexion.middleware.abstract - DEBUG - Adding /stats...
2025-03-05 20:29:51,540 - connexion.operations.openapi3 - DEBUG - consumes: []
2025-03-05 20:29:51,540 - connexion.operations.openapi3 - DEBUG - produces: ['application/json']
2025-03-05 20:29:51,541 - connexion.middleware.swagger_ui - INFO - Adding spec json: /openapi.json
2025-03-05 20:29:51,542 - connexion.middleware.swagger_ui - DEBUG - Adding spec yaml: //openapi.yaml
2025-03-05 20:29:51,543 - connexion.middleware.swagger_ui - DEBUG - Adding swagger-ui: /ui/
2025-03-05 20:30:10,111 - connexion.validators.parameter - DEBUG - /my-first-event validating parameters...
2025-03-05 20:30:10,114 - connexion.decorators.parameter - DEBUG - Query Parameter 'index' (sanitized: 'index') in function arguments
2025-03-05 20:30:10,115 - connexion.decorators.parameter - DEBUG - index is a {'name': 'index', 'in': 'query', 'required': True, 'description': 'The index of the player-performance event in the Kafka queue.', 'schema': {'type': 'integer', 'example': 0}}
2025-03-05 20:30:10,115 - pykafka.cluster - INFO - Broker version is too old to use automatic API version discovery. Falling back to hardcoded versions list.
2025-03-05 20:30:10,115 - pykafka.cluster - DEBUG - Updating cluster, attempt 1/3
2025-03-05 20:30:10,115 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:30:14,230 - pykafka.connection - INFO - Attempt 0: failed to connect to localhost:9092
2025-03-05 20:30:14,231 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:30:14,232 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:30:18,615 - pykafka.connection - INFO - Attempt 1: failed to connect to localhost:9092
2025-03-05 20:30:18,615 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:30:18,615 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:30:23,012 - pykafka.connection - INFO - Attempt 2: failed to connect to localhost:9092
2025-03-05 20:30:23,012 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:30:23,013 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:30:23,314 - pykafka.broker - WARNING - Failed to connect to broker at localhost:9092. Check the `listeners` property in server.config.
2025-03-05 20:30:23,314 - pykafka.cluster - ERROR - Socket disconnected during request for broker localhost:9092. Continuing.
2025-03-05 20:30:23,315 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:30:27,385 - pykafka.connection - INFO - Attempt 0: failed to connect to localhost:9092
2025-03-05 20:30:27,387 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:30:27,387 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:30:31,811 - pykafka.connection - INFO - Attempt 1: failed to connect to localhost:9092
2025-03-05 20:30:31,811 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:30:31,812 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:30:36,187 - pykafka.connection - INFO - Attempt 2: failed to connect to localhost:9092
2025-03-05 20:30:36,187 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:30:36,188 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:30:36,489 - pykafka.broker - WARNING - Failed to connect to broker at localhost:9092. Check the `listeners` property in server.config.
2025-03-05 20:30:36,489 - pykafka.cluster - ERROR - Socket disconnected during request for broker localhost:9092. Continuing.
2025-03-05 20:30:36,491 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:30:40,596 - pykafka.connection - INFO - Attempt 0: failed to connect to localhost:9092
2025-03-05 20:30:40,596 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:30:40,596 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:30:44,971 - pykafka.connection - INFO - Attempt 1: failed to connect to localhost:9092
2025-03-05 20:30:44,971 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:30:44,972 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:30:49,379 - pykafka.connection - INFO - Attempt 2: failed to connect to localhost:9092
2025-03-05 20:30:49,379 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:30:49,379 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:30:49,681 - pykafka.broker - WARNING - Failed to connect to broker at localhost:9092. Check the `listeners` property in server.config.
2025-03-05 20:30:49,681 - pykafka.cluster - ERROR - Socket disconnected during request for broker localhost:9092. Continuing.
2025-03-05 20:30:49,681 - basicLogger - ERROR - Error reading from Kafka: Unable to connect to a broker to fetch metadata. See logs.
2025-03-05 20:30:49,682 - basicLogger - INFO - Found 0 player-performance events in Kafka
2025-03-05 20:30:49,685 - connexion.validators.parameter - DEBUG - /my-first-event validating parameters...
2025-03-05 20:30:49,687 - connexion.decorators.parameter - DEBUG - Query Parameter 'index' (sanitized: 'index') in function arguments
2025-03-05 20:30:49,687 - connexion.decorators.parameter - DEBUG - index is a {'name': 'index', 'in': 'query', 'required': True, 'description': 'The index of the player-performance event in the Kafka queue.', 'schema': {'type': 'integer', 'example': 0}}
2025-03-05 20:30:49,687 - pykafka.cluster - INFO - Broker version is too old to use automatic API version discovery. Falling back to hardcoded versions list.
2025-03-05 20:30:49,687 - pykafka.cluster - DEBUG - Updating cluster, attempt 1/3
2025-03-05 20:30:49,689 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:30:53,774 - pykafka.connection - INFO - Attempt 0: failed to connect to localhost:9092
2025-03-05 20:30:53,774 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:30:53,774 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:30:58,145 - pykafka.connection - INFO - Attempt 1: failed to connect to localhost:9092
2025-03-05 20:30:58,145 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:30:58,146 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:31:02,524 - pykafka.connection - INFO - Attempt 2: failed to connect to localhost:9092
2025-03-05 20:31:02,525 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:31:02,526 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:31:02,827 - pykafka.broker - WARNING - Failed to connect to broker at localhost:9092. Check the `listeners` property in server.config.
2025-03-05 20:31:02,827 - pykafka.cluster - ERROR - Socket disconnected during request for broker localhost:9092. Continuing.
2025-03-05 20:31:02,828 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:31:06,913 - pykafka.connection - INFO - Attempt 0: failed to connect to localhost:9092
2025-03-05 20:31:06,914 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:31:06,914 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:31:11,312 - pykafka.connection - INFO - Attempt 1: failed to connect to localhost:9092
2025-03-05 20:31:11,313 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:31:11,313 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:31:15,717 - pykafka.connection - INFO - Attempt 2: failed to connect to localhost:9092
2025-03-05 20:31:15,717 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:31:15,718 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:31:16,018 - pykafka.broker - WARNING - Failed to connect to broker at localhost:9092. Check the `listeners` property in server.config.
2025-03-05 20:31:16,018 - pykafka.cluster - ERROR - Socket disconnected during request for broker localhost:9092. Continuing.
2025-03-05 20:31:16,018 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:31:20,115 - pykafka.connection - INFO - Attempt 0: failed to connect to localhost:9092
2025-03-05 20:31:20,116 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:31:20,116 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:31:24,505 - pykafka.connection - INFO - Attempt 1: failed to connect to localhost:9092
2025-03-05 20:31:24,505 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:31:24,506 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:31:28,914 - pykafka.connection - INFO - Attempt 2: failed to connect to localhost:9092
2025-03-05 20:31:28,915 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:31:28,915 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:31:29,217 - pykafka.broker - WARNING - Failed to connect to broker at localhost:9092. Check the `listeners` property in server.config.
2025-03-05 20:31:29,218 - pykafka.cluster - ERROR - Socket disconnected during request for broker localhost:9092. Continuing.
2025-03-05 20:31:29,219 - basicLogger - ERROR - Error reading from Kafka: Unable to connect to a broker to fetch metadata. See logs.
2025-03-05 20:31:29,220 - basicLogger - INFO - Found 0 player-performance events in Kafka
2025-03-05 20:31:29,234 - connexion.validators.parameter - DEBUG - /other-event validating parameters...
2025-03-05 20:31:29,236 - connexion.decorators.parameter - DEBUG - Query Parameter 'index' (sanitized: 'index') in function arguments
2025-03-05 20:31:29,237 - connexion.decorators.parameter - DEBUG - index is a {'name': 'index', 'in': 'query', 'required': True, 'description': 'The index of the audience-interaction event in the Kafka queue.', 'schema': {'type': 'integer', 'example': 0}}
2025-03-05 20:31:29,238 - pykafka.cluster - INFO - Broker version is too old to use automatic API version discovery. Falling back to hardcoded versions list.
2025-03-05 20:31:29,239 - pykafka.cluster - DEBUG - Updating cluster, attempt 1/3
2025-03-05 20:31:29,239 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:31:33,336 - pykafka.connection - INFO - Attempt 0: failed to connect to localhost:9092
2025-03-05 20:31:33,337 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:31:33,337 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:31:37,737 - pykafka.connection - INFO - Attempt 1: failed to connect to localhost:9092
2025-03-05 20:31:37,738 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:31:37,738 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:31:42,103 - pykafka.connection - INFO - Attempt 2: failed to connect to localhost:9092
2025-03-05 20:31:42,104 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:31:42,104 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:31:42,405 - pykafka.broker - WARNING - Failed to connect to broker at localhost:9092. Check the `listeners` property in server.config.
2025-03-05 20:31:42,405 - pykafka.cluster - ERROR - Socket disconnected during request for broker localhost:9092. Continuing.
2025-03-05 20:31:42,406 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:31:46,486 - pykafka.connection - INFO - Attempt 0: failed to connect to localhost:9092
2025-03-05 20:31:46,486 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:31:46,487 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:31:50,882 - pykafka.connection - INFO - Attempt 1: failed to connect to localhost:9092
2025-03-05 20:31:50,883 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:31:50,883 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:31:55,271 - pykafka.connection - INFO - Attempt 2: failed to connect to localhost:9092
2025-03-05 20:31:55,272 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:31:55,272 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:31:55,573 - pykafka.broker - WARNING - Failed to connect to broker at localhost:9092. Check the `listeners` property in server.config.
2025-03-05 20:31:55,574 - pykafka.cluster - ERROR - Socket disconnected during request for broker localhost:9092. Continuing.
2025-03-05 20:31:55,575 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:31:59,668 - pykafka.connection - INFO - Attempt 0: failed to connect to localhost:9092
2025-03-05 20:31:59,669 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:31:59,669 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:32:04,058 - pykafka.connection - INFO - Attempt 1: failed to connect to localhost:9092
2025-03-05 20:32:04,058 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:32:04,059 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:32:08,438 - pykafka.connection - INFO - Attempt 2: failed to connect to localhost:9092
2025-03-05 20:32:08,439 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:32:08,439 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:32:08,741 - pykafka.broker - WARNING - Failed to connect to broker at localhost:9092. Check the `listeners` property in server.config.
2025-03-05 20:32:08,741 - pykafka.cluster - ERROR - Socket disconnected during request for broker localhost:9092. Continuing.
2025-03-05 20:32:08,742 - basicLogger - ERROR - Error reading from Kafka: Unable to connect to a broker to fetch metadata. See logs.
2025-03-05 20:32:08,742 - basicLogger - INFO - Found 0 audience-interaction events in Kafka
2025-03-05 20:32:08,747 - connexion.validators.parameter - DEBUG - /other-event validating parameters...
2025-03-05 20:32:08,748 - connexion.decorators.parameter - DEBUG - Query Parameter 'index' (sanitized: 'index') in function arguments
2025-03-05 20:32:08,748 - connexion.decorators.parameter - DEBUG - index is a {'name': 'index', 'in': 'query', 'required': True, 'description': 'The index of the audience-interaction event in the Kafka queue.', 'schema': {'type': 'integer', 'example': 0}}
2025-03-05 20:32:08,749 - pykafka.cluster - INFO - Broker version is too old to use automatic API version discovery. Falling back to hardcoded versions list.
2025-03-05 20:32:08,749 - pykafka.cluster - DEBUG - Updating cluster, attempt 1/3
2025-03-05 20:32:08,750 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:32:12,839 - pykafka.connection - INFO - Attempt 0: failed to connect to localhost:9092
2025-03-05 20:32:12,839 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:32:12,839 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:32:17,224 - pykafka.connection - INFO - Attempt 1: failed to connect to localhost:9092
2025-03-05 20:32:17,224 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:32:17,225 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:32:21,614 - pykafka.connection - INFO - Attempt 2: failed to connect to localhost:9092
2025-03-05 20:32:21,614 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:32:21,615 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:32:21,916 - pykafka.broker - WARNING - Failed to connect to broker at localhost:9092. Check the `listeners` property in server.config.
2025-03-05 20:32:21,916 - pykafka.cluster - ERROR - Socket disconnected during request for broker localhost:9092. Continuing.
2025-03-05 20:32:21,917 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:32:26,001 - pykafka.connection - INFO - Attempt 0: failed to connect to localhost:9092
2025-03-05 20:32:26,001 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:32:26,001 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:32:30,390 - pykafka.connection - INFO - Attempt 1: failed to connect to localhost:9092
2025-03-05 20:32:30,391 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:32:30,391 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:32:34,779 - pykafka.connection - INFO - Attempt 2: failed to connect to localhost:9092
2025-03-05 20:32:34,779 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:32:34,780 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:32:35,081 - pykafka.broker - WARNING - Failed to connect to broker at localhost:9092. Check the `listeners` property in server.config.
2025-03-05 20:32:35,082 - pykafka.cluster - ERROR - Socket disconnected during request for broker localhost:9092. Continuing.
2025-03-05 20:32:35,083 - pykafka.connection - DEBUG - Connecting to localhost:9092
2025-03-05 20:32:39,152 - pykafka.connection - INFO - Attempt 0: failed to connect to localhost:9092
2025-03-05 20:32:39,153 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:32:39,153 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:32:43,528 - pykafka.connection - INFO - Attempt 1: failed to connect to localhost:9092
2025-03-05 20:32:43,529 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:32:43,530 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:32:47,918 - pykafka.connection - INFO - Attempt 2: failed to connect to localhost:9092
2025-03-05 20:32:47,918 - pykafka.connection - INFO - [WinError 10061] No connection could be made because the target machine actively refused it
2025-03-05 20:32:47,919 - pykafka.connection - INFO - Retrying in 300ms.
2025-03-05 20:32:48,220 - pykafka.broker - WARNING - Failed to connect to broker at localhost:9092. Check the `listeners` property in server.config.
2025-03-05 20:32:48,220 - pykafka.cluster - ERROR - Socket disconnected during request for broker localhost:9092. Continuing.
2025-03-05 20:32:48,221 - basicLogger - ERROR - Error reading from Kafka: Unable to connect to a broker to fetch metadata. See logs.
2025-03-05 20:32:48,221 - basicLogger - INFO - Found 0 audience-interaction events in Kafka
